#!/bin/sh

### ./dgis_maps_flutter/example/android/app/build.gradle

cp ./dgis_maps_flutter/example/android/app/build.gradle ./dgis_maps_flutter/example/android/app/build.gradle.bak
sed -i '' -e 's/applicationId ".*"/applicationId "pro.flown.dgis_maps_flutter_android_example"/' ./dgis_maps_flutter/example/android/app/build.gradle
git add ./dgis_maps_flutter/example/android/app/build.gradle
mv ./dgis_maps_flutter/example/android/app/build.gradle.bak ./dgis_maps_flutter/example/android/app/build.gradle


### ./dgis_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj

cp ./dgis_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj ./dgis_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj.bak
sed -i '' -e 's/PRODUCT_BUNDLE_IDENTIFIER = .*;/PRODUCT_BUNDLE_IDENTIFIER = pro.flown.dgis_maps_flutter_ios_example;/g' ./dgis_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
git add ./dgis_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
mv ./dgis_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj.bak ./dgis_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
