// Autogenerated from Pigeon (v7.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class CreationParams {
  CreationParams({
    required this.position,
    required this.zoom,
  });

  LatLng position;

  double zoom;

  Object encode() {
    return <Object?>[
      position.encode(),
      zoom,
    ];
  }

  static CreationParams decode(Object result) {
    result as List<Object?>;
    return CreationParams(
      position: LatLng.decode(result[0]! as List<Object?>),
      zoom: result[1]! as double,
    );
  }
}

class LatLng {
  LatLng({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  Object encode() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  static LatLng decode(Object result) {
    result as List<Object?>;
    return LatLng(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }
}

class MarkerBitmap {
  MarkerBitmap({
    required this.bytes,
    this.width,
    this.height,
  });

  /// Байты изображения
  Uint8List bytes;

  /// Ширина изображения,
  /// если null, используется значение по умолчанию,
  /// которое зависит от нативной реализации
  double? width;

  /// Высота изображения,
  /// если null, используется значение по умолчанию,
  /// которое зависит от нативной реализации
  double? height;

  Object encode() {
    return <Object?>[
      bytes,
      width,
      height,
    ];
  }

  static MarkerBitmap decode(Object result) {
    result as List<Object?>;
    return MarkerBitmap(
      bytes: result[0]! as Uint8List,
      width: result[1] as double?,
      height: result[2] as double?,
    );
  }
}

class Marker {
  Marker({
    required this.markerId,
    this.bitmap,
    required this.position,
    this.infoText,
  });

  /// Уникальный идентификатор маркера
  MarkerId markerId;

  /// Изображение маркера
  /// Используется нативная реализация дефолтного маркера,
  /// если null
  MarkerBitmap? bitmap;

  /// Позиция маркера
  LatLng position;

  /// Текст под маркером
  String? infoText;

  Object encode() {
    return <Object?>[
      markerId.encode(),
      bitmap?.encode(),
      position.encode(),
      infoText,
    ];
  }

  static Marker decode(Object result) {
    result as List<Object?>;
    return Marker(
      markerId: MarkerId.decode(result[0]! as List<Object?>),
      bitmap: result[1] != null
          ? MarkerBitmap.decode(result[1]! as List<Object?>)
          : null,
      position: LatLng.decode(result[2]! as List<Object?>),
      infoText: result[3] as String?,
    );
  }
}

class MarkerId {
  MarkerId({
    required this.value,
  });

  String value;

  Object encode() {
    return <Object?>[
      value,
    ];
  }

  static MarkerId decode(Object result) {
    result as List<Object?>;
    return MarkerId(
      value: result[0]! as String,
    );
  }
}

class _PluginHostApiCodec extends StandardMessageCodec {
  const _PluginHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LatLng) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is Marker) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is MarkerBitmap) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is MarkerId) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return LatLng.decode(readValue(buffer)!);
      
      case 129:       
        return Marker.decode(readValue(buffer)!);
      
      case 130:       
        return MarkerBitmap.decode(readValue(buffer)!);
      
      case 131:       
        return MarkerId.decode(readValue(buffer)!);
      
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PluginHostApi {
  /// Constructor for [PluginHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PluginHostApi({BinaryMessenger? binaryMessenger, this.id})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;
  final int? id;

  static const MessageCodec<Object?> codec = _PluginHostApiCodec();

  Future<LatLng> asy(LatLng arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'pro.flown.PluginHostApi_$id.asy', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as LatLng?)!;
    }
  }

  Future<Marker> m(Marker arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'pro.flown.PluginHostApi_$id.m', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as Marker?)!;
    }
  }
}

class _PluginFlutterApiCodec extends StandardMessageCodec {
  const _PluginFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LatLng) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return LatLng.decode(readValue(buffer)!);
      
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class PluginFlutterApi {
  static const MessageCodec<Object?> codec = _PluginFlutterApiCodec();

  Future<LatLng> asy(LatLng msg);

  LatLng sy(LatLng msg);

  static void setup(PluginFlutterApi? api, {BinaryMessenger? binaryMessenger, int? id}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'pro.flown.PluginFlutterApi_$id.asy', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for pro.flown.PluginFlutterApi_$id.asy was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LatLng? arg_msg = (args[0] as LatLng?);
          assert(arg_msg != null,
              'Argument for pro.flown.PluginFlutterApi_$id.asy was null, expected non-null LatLng.');
          final LatLng output = await api.asy(arg_msg!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'pro.flown.PluginFlutterApi_$id.sy', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for pro.flown.PluginFlutterApi_$id.sy was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LatLng? arg_msg = (args[0] as LatLng?);
          assert(arg_msg != null,
              'Argument for pro.flown.PluginFlutterApi_$id.sy was null, expected non-null LatLng.');
          final LatLng output = api.sy(arg_msg!);
          return output;
        });
      }
    }
  }
}
