// Autogenerated from Pigeon (v7.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class LatLng {
  LatLng({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  Object encode() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  static LatLng decode(Object result) {
    result as List<Object?>;
    return LatLng(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }
}

class _PluginHostApiCodec extends StandardMessageCodec {
  const _PluginHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LatLng) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return LatLng.decode(readValue(buffer)!);
      
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PluginHostApi {
  /// Constructor for [PluginHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PluginHostApi({BinaryMessenger? binaryMessenger, this.id})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;
  final int? id;

  static const MessageCodec<Object?> codec = _PluginHostApiCodec();

  Future<LatLng> asy(LatLng arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'pro.flown.PluginHostApi_$id.asy', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as LatLng?)!;
    }
  }

  Future<LatLng> sy(LatLng arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'pro.flown.PluginHostApi_$id.sy', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as LatLng?)!;
    }
  }
}

class _PluginFlutterApiCodec extends StandardMessageCodec {
  const _PluginFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LatLng) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return LatLng.decode(readValue(buffer)!);
      
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class PluginFlutterApi {
  static const MessageCodec<Object?> codec = _PluginFlutterApiCodec();

  Future<LatLng> asy(LatLng msg);

  LatLng sy(LatLng msg);

  static void setup(PluginFlutterApi? api, {BinaryMessenger? binaryMessenger, int? id}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'pro.flown.PluginFlutterApi_$id.asy', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for pro.flown.PluginFlutterApi_$id.asy was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LatLng? arg_msg = (args[0] as LatLng?);
          assert(arg_msg != null,
              'Argument for pro.flown.PluginFlutterApi_$id.asy was null, expected non-null LatLng.');
          final LatLng output = await api.asy(arg_msg!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'pro.flown.PluginFlutterApi_$id.sy', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for pro.flown.PluginFlutterApi_$id.sy was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LatLng? arg_msg = (args[0] as LatLng?);
          assert(arg_msg != null,
              'Argument for pro.flown.PluginFlutterApi_$id.sy was null, expected non-null LatLng.');
          final LatLng output = api.sy(arg_msg!);
          return output;
        });
      }
    }
  }
}
